import Head from 'next/head'
import LinksWrapper from '../components/LinksWrapper/LinksWrapper'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>fb - tools</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LinksWrapper />
      </main>
    </div>
  )
}
